### ISSUE TITLE
SuiteB Encryption/Decryption works in 1.4.0.0 but fails in 1.5.0.0

### ISSUE THREAD

**Issue by Lorentzen1337** [sdrapkin/SecurityDriven.Inferno#19]
Hi @sdrapkin 
First of all thanks for an amazing library!
I am having issues with an implementation that works fine under 1.4.0.0 but fails in 1.5.0.0.
Inspiration for the following has been taken from your comment in another issue: [A trivial code sample](https://github.com/sdrapkin/SecurityDriven.Inferno/issues/8#issuecomment-217471990)

I made a simple console app to demonstrate the behaviour:
`using SecurityDriven.Inferno.Extensions;
using System;

namespace SecurityDriven.Inferno.ConsoleApp
{
    internal static class Program
    {
        private static readonly byte[] masterKey = new byte[3] { 1, 2, 3 };
        private static readonly CryptoRandom rnd = new CryptoRandom();

        private static void Main(string[] args)
        {
            string plainPassword = "THIS IS A PLAIN PASSWORD";
            var saltByteArr = new byte[rnd.Next(0, 64)];
            rnd.NextBytes(saltByteArr);
            var encryptedPassword = Encrypt(plainPassword, saltByteArr.ToB64Url());

            Console.WriteLine("Plain password: " + plainPassword);
            Console.WriteLine("Encrypted password: " + encryptedPassword);
            Console.WriteLine("Decrypted password: " + Decrypt(encryptedPassword, saltByteArr.ToB64Url()));
            Console.Read();
        }

        public static string Encrypt(string plainPassword, string salt)
        {
            var passwordArrSeg = Utils.SafeUTF8.GetBytes(plainPassword).AsArraySegment();
            var saltArrSeg = salt.FromB64Url().AsArraySegment();
            var encryptedPassword = SuiteB.Encrypt(masterKey, passwordArrSeg, saltArrSeg);

            return encryptedPassword.ToB64Url();
        }

        public static string Decrypt(string encryptedPassword, string salt)
        {
            var encryptedPasswordArrSeg = encryptedPassword.FromB64Url().AsArraySegment();
            var saltArrSeg = salt.FromB64Url().AsArraySegment();
            var saltLength = saltArrSeg.Count;
            var encryptedPassword_and_salt = Utils.Combine(saltArrSeg.Array, encryptedPasswordArrSeg.Array);

            var decryptedPassword = SuiteB.Decrypt(
                masterKey,
                new ArraySegment<byte>(encryptedPassword_and_salt, saltLength, encryptedPassword_and_salt.Length - saltLength),
                new ArraySegment<byte>(encryptedPassword_and_salt, 0, saltLength)
                );

            return Utils.SafeUTF8.GetString(decryptedPassword);
        }
    }
}`

In 1.4.0.0 the code above results in correct encryption/decryption however in 1.5.0.0 targeting 4.6.2 it seems that the decryption at least fails as `Utils.SafeUTF8.GetString(decryptedPassword);` results in conversion errors due to bytes not being able to translate to unicode.

The exception looks like this:
> System.Text.DecoderFallbackException
  HResult=0x80070057
  Message=Unable to translate bytes [D2] at index 0 from specified code page to Unicode.
  Source=mscorlib
  StackTrace:
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBytes)
   at System.Text.UTF8Encoding.GetCharCount(Byte* bytes, Int32 count, DecoderNLS baseDecoder)
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at System.Text.Encoding.GetString(Byte[] bytes)
   at SecurityDriven.Inferno.ConsoleApp.Program.Decrypt(String encryptedPassword, String salt) in C:\_projects\SecurityDriven.Inferno\Latest\SecurityDriven.Inferno.ConsoleApp\Program.cs:line 46
   at SecurityDriven.Inferno.ConsoleApp.Program.Main(String[] args) in C:\_projects\SecurityDriven.Inferno\Latest\SecurityDriven.Inferno.ConsoleApp\Program.cs:line 20

Any help would be appreciated!

**Comment by sdrapkin** [comment]
It is a serious bug. Thanks for reporting it.
The bug was introduced in d1f958d7c093fd3c54d3aeb25bd489f90b2f1565.
The bug is not fixed in 40962ef17271b182580759618afa179b65526ced.
New Nuget and Github builds will be available shortly.
Unit tests did not cover this scenario, and missed this regression - will also be updated.

**Comment by Lorentzen1337** [comment]
No problem man!
Thanks for the quick fix 👍

**Comment by sdrapkin** [comment]
New build 1.5.1 has been released, which fixes the regression. Unit tests has also been updated.
```
Install-Package Inferno -Version 1.5.1
```

**Comment by henning-krause** [comment]
@sdrapkin, great to hear that. Could you also update the strong-named package? That would be great.

**Comment by sdrapkin** [comment]
@henning-krause [Inferno.StrongName 1.5.1](https://www.nuget.org/packages/Inferno.StrongName/1.5.1)

**Comment by henning-krause** [comment]
Thank you!
