### ISSUE TITLE
mac dotnet core: The type initializer for 'SecurityDriven.Inferno.EtM_CTR' threw an exception: Unable to load shared library 'bcrypt.dll' or one of its dependencies

### ISSUE THREAD

**Issue by davious** [sdrapkin/SecurityDriven.Inferno#21]
Hi,

I am attempting to use SuiteB.Encrypt on a mac net dotcore project.
When I call it I get the following stack trace:
```
System.TypeInitializationException: The type initializer for 'SecurityDriven.Inferno.EtM_CTR' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SecurityDriven.Inferno.CryptoRandom' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'bcrypt.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libbcrypt.dll, 1): image not found
   at SecurityDriven.Inferno.BCrypt.BCryptGenRandom(IntPtr hAlgorithm, Byte[] pbBuffer, Int32 cbBuffer, Int32 dwFlags)
   at SecurityDriven.Inferno.CryptoRandom.SanityCheck() in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\CryptoRandom.cs:line 39
   at SecurityDriven.Inferno.CryptoRandom..cctor() in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\CryptoRandom.cs:line 24
   --- End of inner exception stack trace ---
   at SecurityDriven.Inferno.CryptoRandom..ctor() in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\CryptoRandom.cs:line 18
   at SecurityDriven.Inferno.EtM_CTR..cctor() in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\EtM_CTR.cs:line 12
   --- End of inner exception stack trace ---
   at SecurityDriven.Inferno.EtM_CTR.Encrypt(Byte[] masterKey, ArraySegment`1 plaintext, Byte[] output, Int32 outputOffset, Nullable`1 salt, UInt32 counter) in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\EtM_CTR.cs:line 48
   at SecurityDriven.Inferno.EtM_CTR.Encrypt(Byte[] masterKey, ArraySegment`1 plaintext, Nullable`1 salt, UInt32 counter) in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\EtM_CTR.cs:line 91
   at SecurityDriven.Inferno.SuiteB.Encrypt(Byte[] masterKey, ArraySegment`1 plaintext, Nullable`1 salt) in C:\Users\sdrapkin\Dropbox\Code\SecurityDriven.Inferno\SuiteB.cs:line 14
```

May I have your help getting Inferno running?

**Comment by sdrapkin** [comment]
@davious Inferno uses Windows-native crypto primitives, and while it does support dotnetcore Inferno only runs on Windows.

**Comment by jefflafay** [comment]
Any chance that you will be supporting Mac OS or Linux in the future with some other crypto dependencies? I need this to work with Mac OS.

**Comment by sdrapkin** [comment]
@jefflafay Inferno currently has a lot of internal dependencies on Windows-native APIs - mostly for performance reasons. While it should be possible to remove some of these dependencies in lieu of NetStandard-APIs only (at at the expense of performance), I don't currently have plans to do so. This would ideally require proper target-platform testing as well (I don't own a Mac).
