### ISSUE TITLE
`CngKeyExtensions.GetSharedDhmSecret()` fails on .NET core

### ISSUE THREAD

**Issue by ronnieoverby** [sdrapkin/SecurityDriven.Inferno#30]
I'm using this package version: https://www.nuget.org/packages/Inferno/1.6.0.1

[Your key exchange example](https://securitydriven.net/inferno#DHM%20Key%20Exchange) is failing on .NET Core:

```C#
void Main()
{
	var keyA = CngKeyExtensions.CreateNewDhmKey();
	var keyB = CngKeyExtensions.CreateNewDhmKey();

	var staticSharedSecret = keyA.GetSharedDhmSecret(publicDhmKey: keyB); // EXCEPTION HERE
	staticSharedSecret.ToB64().Dump("staticSharedSecret"); // static for a given {private key A, public key B} pair

	var ephemeralBundle = keyB.GetSharedEphemeralDhmSecret();

	// must be communicated to B so that B can also derive the ephemeral shared secret
	ephemeralBundle.EphemeralDhmPublicKeyBlob.ToB64().Dump("ephemeral public DHM key");

	// the ephemeral private key is forgotten by A
	ephemeralBundle.SharedSecret.ToB64().Dump("ephemeralSharedSecret");
}
```

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=The specified curve 'nistP384' or its parameters are not valid for this platform.
  Source=System.Security.Cryptography.Algorithms
  StackTrace:
   at System.Security.Cryptography.ECCng.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, String curveName, SafeNCryptProviderHandle provider)
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, Byte[] keyBlob, String curveName)
   at System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportKeyBlob(Byte[] ecKeyBlob, String curveName, Boolean includePrivateParameters)
   at System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportParameters(ECParameters parameters)
   at System.Security.Cryptography.ECDiffieHellman.Create(ECParameters parameters)
   at SecurityDriven.Inferno.Extensions.CngKeyExtensions.GetSharedDhmSecret(CngKey privateDhmKey, CngKey publicDhmKey, Byte[] contextAppend, Byte[] contextPrepend)
   at ftx.Program.CreateServerEncryptor(BinaryReader reader, BinaryWriter writer) in C:\code\ro\ftx\src\ftx\Program.cs:line 161
   at ftx.Program.RunServer(ProgramOptions options) in C:\code\ro\ftx\src\ftx\Program.cs:line 51
   at ftx.Program.Main(String[] args) in C:\code\ro\ftx\src\ftx\Program.cs:line 19

Inner Exception 1:
WindowsCryptographicException: The parameter is incorrect.
```
I see a .net core specific implementation  at https://github.com/sdrapkin/SecurityDriven.Inferno/blob/65059fcf1fcd1c4e1302cfba9ecc0675d9413b84/Extensions/CngKeyExtensions.cs#L52-L93 and I'm wondering under what circumstances this is expected to work properly.

Thank you.

**Comment by sdrapkin** [comment]
@ronnieoverby Thanks for reporting it. I'm able to reproduce, and confirm that it's a bug.
The offending line is [here](https://github.com/sdrapkin/SecurityDriven.Inferno/blob/65059fcf1fcd1c4e1302cfba9ecc0675d9413b84/Extensions/CngKeyExtensions.cs#L80). It's a classic copy-paste mistake (should be `public..`). 😥

The [test-suite](https://github.com/sdrapkin/SecurityDriven.Inferno.Tests) was not robust enough to catch it - I'll be fixing that as well.

**Comment by ronnieoverby** [comment]
I'm really glad that I wasn't missing something! 

Thanks again for your efforts.

**Comment by sdrapkin** [comment]
I pushed [Inferno v1.6.2](https://www.nuget.org/packages/Inferno/1.6.2) to Nuget. Please give it a try.

**Comment by ronnieoverby** [comment]
Fixed. Thanks!
